### ISSUE TITLE
fix docker images

### ISSUE THREAD

**Issue by cwmeijer** [nlesc-sherlock/deeplearning#105]
- [x] scripts need relative paths to input directory
- [x] ~entrypoints need to be /bin/bash~ entrypoints must be empty, then run the command from CWL
- [x] move scripts to directory where the docker image is
- [x] rebuild docker images (boatswain)

car model is already work in progress

**Comment by egpbos** [comment]
Need to fix: all Docker images after first crop, i.e.:
- [x] car color workflow (and everything it depends on, that goes for all of them)
- [x] car model workflow
- [x] face detector workflow minimal
- [x] person face gender workflow
- [x] person face age workflow

After face detect is another crop that also needs fixing.
- [x] Maybe

**Comment by egpbos** [comment]
Dependency tree of all Docker images (also put this in boatswain.yml):

BASE IMAGES (only used as dependency, not for running):
docker/base/caffe-nv --> _nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04_
docker/base/image_classify --> docker/base/caffe-nv

BARE RUNNABLE IMAGES (runs bare Python script):
docker/cnn_classify --> docker/base/image_classify
docker/car/color --> docker/cnn_classify

JSON-WRAPPED RUNNABLE IMAGES (runs with cwltool, wraps bare scripts in custom json format):
docker/car/color-wrapper --> docker/car/color

**Comment by egpbos** [comment]
Age still buggy
