### ISSUE TITLE
Performance of a pre-trained network

### ISSUE THREAD

**Issue by elboyran** [nlesc-sherlock/deeplearning#17]
Investigate how to measure (verify reported) performance of a pre-trained network in DIGITS.

**Comment by bpmweel** [comment]
This github shows how to take a DIGITS model and apply it to a dataset.
https://github.com/NVIDIA/DIGITS/tree/master/examples/classification

**Comment by elboyran** [comment]
1. Find out what is the 'base' architecture of the Age/Gender networks
2. Try loading Adience faces and pre-trained network models in DIGITS
3. Try creating a network from the pre-trained without learning
4. Try to obtain performance.

**Comment by elboyran** [comment]
2.1 Generate Adience gender DIGITS Dataset
2.2. Generate Age gender DIGITS Dataset

**Comment by elboyran** [comment]
Adience pre-trained model configuration file cannot be loaded in DIGITS

**Comment by elboyran** [comment]
Instead 2. Try loading CompCars (lotsacars) and the pre-trained model into DIGITS

**Comment by elboyran** [comment]
The pre-trained CompCars model can be loaded into DIGITS, but no the configuration. Luckily, it's based on GoogLeNet, whose standard configuration could be used.

**Comment by elboyran** [comment]
Importing pre-trained CompCars model and using it with 1 epoch training only (trick) doesn't give any good/reasonable performance. Conclusion- do not use other people's models in DIGITS.
