### ISSUE TITLE
scrape a dataset from google images

### ISSUE THREAD

**Issue by cwmeijer** [nlesc-sherlock/deeplearning#21]
- [x] 1: Get a list of car makes. (dbpedia? dutch car website?)
- [x] 2: Get a list of models for each make.
- [x] 3. Get urls from google images api using the terms '<make> <model> te koop'. Adding the 'te koop' gets you more realistic images hopefully. Maybe adding a year would help as well to get more homogeneous classes.
- [x] 4. Come up with some smart criterium when to stop retrieving urls. (like, first 100 results, or first 10% or after n non cars or whatever)
- [ ] 5. Run each image through the classification docker to make sure it is a car.

If we scrape the urls separately from the images there should be no legal issues and I think we might even be able to publish the urls as a labeled dataset. Also, because images are on separate servers we don't have to be afraid to overload any server.

**Comment by ridderl** [comment]
Google images api seems to be deprecated:
http://stackoverflow.com/questions/533857/whats-the-best-web-image-search-api

Using the generic googlesearch  API from python works like below. But don't know yet if this can be used for getting images urls.

```
import requests

def googlesearch(query):
    link = 'http://ajax.googleapis.com/ajax/services/search/web?v=1.0&%s' % query
    payload = {'q': query}
    response = requests.get(link, params=payload)
    print response.text

googlesearch('test')
```

**Comment by ridderl** [comment]
Changing "web" to  "images" in the above code results in:

```
{"responseData": null, "responseDetails": "This API is no longer available.", "responseStatus": 403}
```

**Comment by cwmeijer** [comment]
Points 1 and 2 are done, the resulting csv is in the current repo under /results/carmodels

**Comment by ridderl** [comment]
Points 3 and 4 are done.
I used the Bing search API, which allows 5000 transactions of 50 search results per month for free. The script "search_bing.py" retrieves 50 image urls for each car model in results/carmodels.csv and stores them in the SQLite file results/carmodels.db. I ran the script twice, second time with offset 51, so we have up to 100 image urls per model now.
