### ISSUE TITLE
Prepare small demo set of car images to classify

### ISSUE THREAD

**Issue by elboyran** [nlesc-sherlock/deeplearning#24]
Make list of car demo images to classify in DIGITS
Make demo set for use by the docker classifier(?)

**Comment by egpbos** [comment]
Perhaps it is nice to make several categories based on image quality and/or image context, e.g. "good" vs "noisy", "partial car", "multiple objects".

**Comment by elboyran** [comment]
Yes, but not sure though if it'll work well/at all on any of the no "good" category ;-)

**Comment by egpbos** [comment]
True, but that's science :P

Within the "good" category you could also subdivide into "stock" (perfect manufacturer-supplied commercial images), "seller" (if we find any good images of people selling their cars via internet), "road" (google for nice images of cars on the road, possibly surrounded by other cars), "city" (buildings around) and "country" (offroad, country-side, etc).

Perhaps a bit too much detail, but I'm just brainstorming.

The nice thing about such a dataset is that it may tell us more about where the algorithm performs well and where it doesn't, which we could then perhaps use to improve the model as well.

However, probably this will be too much work, so maybe we should look if such a dataset already exists. And if not, then forget it ;)
