### ISSUE TITLE
Demonstrate age/gender classification

### ISSUE THREAD

**Issue by elboyran** [nlesc-sherlock/deeplearning#27]

**Comment by elboyran** [comment]
Preferably both using DIGITS and using our generic docker

**Comment by ridderl** [comment]
Did we consider face recognition? http://arxiv.org/pdf/1504.02351v1.pdf 
How about trying a binary model "Holleeder vs Non-Holleeder". We could demo identifying Holleeder in a random set of faces ....

**Comment by elboyran** [comment]
We have enough work on the usecases already (I think) and face recognition is too wide-spread to look into it.

Sent from Samsung tablet

-------- Original message --------

**Comment by ridderl** [comment]
I thought we could do this instead of the planned gun model. (For me recognizing Holleeder would be much more fun for the demo than classifying guns.) And a binary model could be relatively simple/feasible?
