### ISSUE TITLE
Change cnn_classify.py output to JSON

### ISSUE THREAD

**Issue by egpbos** [nlesc-sherlock/deeplearning#28]
Script now prints unparseable stuff. Change to nice machine readable JSON.

**Comment by elboyran** [comment]
So, the problem with input wildcards is solved?

Sent from Samsung Mobile

-------- Original message --------
From: Patrick Bos
Date:18/02/2016 09:17 (GMT+01:00)
To: nlesc-sherlock/deeplearning
Subject: [deeplearning] Change cnn_classify.py output to JSON (#28)

Script now prints unparseable stuff. Change to nice machine readable JSON.

##

**Comment by bpmweel** [comment]
Patrick and I are working on both issues in parallel. Things should be possible to resolve today.

**Comment by elboyran** [comment]
Succes!

Sent from Samsung Mobile

-------- Original message --------
From: Berend Weel
Date:18/02/2016 10:31 (GMT+01:00)
To: nlesc-sherlock/deeplearning
Cc: Elena Ranguelova
Subject: Re: [deeplearning] Change cnn_classify.py output to JSON (#28)

Patrick and I are working on both issues in parallel. Things should be possible to resolve today.
