### ISSUE TITLE
Set up caffe and DIGITS on own DAS-5 accounts

### ISSUE THREAD

**Issue by elboyran** [nlesc-sherlock/deeplearning#3]

**Comment by bpmweel** [comment]
@ridderl

**Comment by bpmweel** [comment]
I've written the process of setting up the digits server in https://github.com/nlesc-sherlock/deeplearning/blob/master/startdocuments/digits-quickinstall-das5.md

**Comment by egpbos** [comment]
Can we close? Did everyone finish?
- [ ] @bpmweel 
- [x] @cwmeijer 
- [x] @elboyran 
- [ ] @Maartenvm 
- [x] @ridderl
