### ISSUE TITLE
Learn how to fine-tune a model in DIGITS/Caffe 

### ISSUE THREAD

**Issue by cwmeijer** [nlesc-sherlock/deeplearning#37]
Continuation of issues #16 and related to #9

**Comment by egpbos** [comment]
@bpmweel is trying (essentially) this approach: https://github.com/NVIDIA/DIGITS/tree/master/examples/fine-tuning

**Comment by elboyran** [comment]
Nice. Let me know if the prototxt trick works for GoogleNet (that's one used for the cars, right?).

**Comment by egpbos** [comment]
Another possible approach is given here, I'm going to try this: https://github.com/NVIDIA/DIGITS/issues/49

**Comment by egpbos** [comment]
Current status: we are able to load back pretrained models (#9). Next question is how to set the model so that it will not recompute all the weights (which it will by default). @bpmweel found that you can set lm-param to zero, that could be it.

**Comment by bpmweel** [comment]
When you download caffe there are a number of examples in the git repo. One is called finetune_flickr_style. The readme there has some good explanation on how to do finetuning https://github.com/BVLC/caffe/tree/master/examples/finetune_flickr_style

**Comment by bpmweel** [comment]
There is also a fine-tuning ipython notebook that we can probably use
