### ISSUE TITLE
Check state of model docker image

### ISSUE THREAD

**Issue by cwmeijer** [nlesc-sherlock/deeplearning#38]
Make sure it works as nicely (somewhat userfriendly)

**Comment by bpmweel** [comment]
The model docker can run any model on a set of images using the correct invocation. The script to use for this is ccn_classify.py (which runs in the docker).

The invocation needs to make sure that:
1. The model directory is mounted in the docker using the -v command (convention is /model)
2. The data directory is mounter in the docker using the -v command (convention is /data)
3. Let the script know which model directory to use: e.g. -M /model
4. Give the script a list of images to classify (for instance *.jpg)

For more options see the cnn_classify.py script
