### ISSUE TITLE
Set up a VM on the SURF Sara HPC cloud on a node with GPU

### ISSUE THREAD

**Issue by elboyran** [nlesc-sherlock/deeplearning#4]

**Comment by egpbos** [comment]
VM with two GPUs running, Docker container with DIGITS server running as daemon. [Howto here](https://github.com/nlesc-sherlock/deeplearning/blob/d459d2d3e90152aacb29a3975849eb43e0e5c53f/startdocuments/SetupSaraVM.md).

**Comment by egpbos** [comment]
Will be tested by second party (@maartenvm?).

**Comment by egpbos** [comment]
`nvidia-docker` broke, see #31
