### ISSUE TITLE
train a car network on new dataset

### ISSUE THREAD

**Issue by cwmeijer** [nlesc-sherlock/deeplearning#50]

**Comment by elboyran** [comment]
Very relevant paper for choosing the model to train:
[Paper](http://cs231n.stanford.edu/reports/lediurfinal.pdf)

**Comment by elboyran** [comment]
Should upload the trained model files in git!

**Comment by elboyran** [comment]
Looking in how to do automatic hyper parameter sweep with DIGITS.

**Comment by Maartenvm** [comment]
Used this network structure to finetune the CompCars network:
https://github.com/nlesc-sherlock/deeplearning/blob/master/Models/lotsacars-20151202-170935-03d3/fixed_lotsacars_train_val.prototxt

Hyperparameters that showed promise on the subset:
https://github.com/nlesc-sherlock/deeplearning/blob/master/Models/hyperparameters
