### ISSUE TITLE
Create component that crops

### ISSUE THREAD

**Issue by cwmeijer** [nlesc-sherlock/deeplearning#60]
Take YOLO or Viola Jones, or similar component bounding boxes as input

**Comment by ridderl** [comment]
Currently the CWL workflow is using imagemagick for cropping. I propose we stick with that until there is a clear need to make something else.

**Comment by egpbos** [comment]
@ridderl did you commit the crop component?

**Comment by elboyran** [comment]
@ridderl And the workflow?

**Comment by ridderl** [comment]
Yes. Are these commits invisible to you?
I created a folder CWLworkflow for these.

**Comment by egpbos** [comment]
Ah right, thx!
