### ISSUE TITLE
Gender component classifyer

### ISSUE THREAD

**Issue by cwmeijer** [nlesc-sherlock/deeplearning#62]
Create a component that classifies faces as either male or female and gives an age estimate

**Comment by egpbos** [comment]
Looking at GoogleNet AgeGender model @ DIGITS server (    /data/lib/DIGITS-5.0.0-rc.1/digits/jobs/20161108-091520-60bd). Doesn't seem to have mean.binaryproto and labels files...

**Comment by elboyran** [comment]
When using Download butting from the DIGITS interface, we download the model with all necessary files in the model's folder. We should commit this folder in our repo int he Models folder!

**Comment by elboyran** [comment]
Updated the Dockerfile for cc-image-classify. Commit 98c2b51

**Comment by egpbos** [comment]
Done.

**Comment by egpbos** [comment]
Example on HPC cloud VM (dl-primus):
```sh
docker pull nlescsherlockdl/caffe_image_classify
DATADIR=/data/patrick_data/faces
MODELDIR=/data/patrick_models/20161212_googlenet_agegender
SNAPFILE=snapshot_iter_1665.caffemodel
nvidia-docker run \
    -v $DATADIR:/data \
    -v $MODELDIR:/model \
    nlescsherlockdl/caffe_image_classify \
    -v --batch_size=59 \
    -M /model \
    --model_snapshot $SNAPFILE \
    -D /data `ls $DATADIR`
```

Add `--gpu_id=0` to use GPU 0 (=1 to use GPU 1, etc. if you have several GPUs). CPU version is a lot slower, of course.

**Comment by egpbos** [comment]
Updated https://github.com/nlesc-sherlock/deeplearning/blob/master/docker/caffe_image_classify/README.md with example.

**Comment by egpbos** [comment]
We still have to build a specific model docker for this.

**Comment by egpbos** [comment]
Gender model v0.1 created. Put on DockerHub (https://hub.docker.com/r/nlescsherlockdl/image_classify_gender/). Does not have JSON input yet (#76) and JSON output is in wrong format (#75).
