### ISSUE TITLE
Create YOLO component

### ISSUE THREAD

**Issue by cwmeijer** [nlesc-sherlock/deeplearning#64]
A YOLO docker image already exists but it's lacking a command and its output needs to be filtered.

**Comment by ridderl** [comment]
Hi Christiaan, can you warn me when the YOLO docker image in dockerhub is updated. The command is most important, I can do the filtering in a CWL component.

**Comment by cwmeijer** [comment]
I've uploaded the YOLO docker. Assuming you have kpkoningsplnsingel.jpg in your current workind dir, you can now call it like:

docker run -v $PWD:/data/ nlescsherlockdl/yolo /data/kpkoningsplnsingel.jpg

The output is still unfiltered. I could filter the output, that will take 15 minutes I guess as it's already in a python script. Or do you want to do that in CWL? You could let me filter the output so you could use that time to try to filter certain images and send them to different components like we discussed yesterday.

**Comment by ridderl** [comment]
I thought I could first try to implement something like: take most likely Car box, crop it, and send it to next classification component.

**Comment by ridderl** [comment]
Then I will have to go through the output anyway. I want to try to do this with awk inside a CWL component. Will let you know if that works.

**Comment by cwmeijer** [comment]
Alright, then I won't filter it for now. I may update it to clean up a bit but I won't change the functionality.

**Comment by ridderl** [comment]
CWL tries to run it in such a way that it cause an error:

```
sudo  docker run -i \
--volume=/home/lars/deeplearning/CWLworkflow/carandbike.jpeg:/var/lib/cwl/stgd3ac2f38-096c-4af8-b20e-58bc0084f54b/carandbike.jpeg:ro   \
--volume=/tmp/tmpmXp4Wk:/var/spool/cwl:rw   \
--volume=/tmp/tmpvxcI8a:/tmp:rw     \
--workdir=/var/spool/cwl     \
--read-only=true     \
--log-driver=none     \
--user=0     --rm     \
--env=TMPDIR=/tmp     \
--env=HOME=/var/spool/cwl    \
nlescsherlockdl/yolo     \
/var/lib/cwl/stgd3ac2f38-096c-4af8-b20e-58bc0084f54b/carandbike.jpeg

Traceback (most recent call last):
  File "/scripts/run_yolo.py", line 15, in <module>
    subprocess.call(command)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Is scripts/run_yolo.py from of the yolo repository, or did you write that script?

**Comment by cwmeijer** [comment]
I wrote it, it's in /scripts/ in the docker image.

**Comment by ridderl** [comment]
Can you tell why the above docker command fails? A similar call worked for the imagenet1000 docker image. Do we need the python script? Would it be possible to just use `./darknet yolo test cfg/yolo.cfg yolo.weights` as the Docker CMD?

**Comment by cwmeijer** [comment]
Yes this would be possible. I inserted the python script mainly to be able to filter the output later on.

What message do you get when the command fails?

**Comment by ridderl** [comment]
Please check the message above (in the issue in github), it shows the traceback.
