### ISSUE TITLE
Person face gender workflow docker

### ISSUE THREAD

**Issue by cwmeijer** [nlesc-sherlock/deeplearning#85]
A docker image that is based on the general docker (#84). It will accept project specific json as input, adds its results to it and outputs this augmented json file.
- [x] wrapper on github in workflowdocker/<purposename> directory
- [x] on dockerhub (nlescsherlockdl/<purposename>-workflow)

**Comment by egpbos** [comment]
Working docker image and wrapper script generated! Now pushing to dockerhub.

**Comment by egpbos** [comment]
https://hub.docker.com/r/nlescsherlockdl/image_classify_gender_workflow/

See dockerfile for run example (docker/image_classify/workflow_wrap/gender/Dockerfile).

**Comment by cwmeijer** [comment]
Did you pick a threshold? We looked at about 15 nlesc people and 0.6 seems a good probability cutoff. Only 2 people would be undefined and ther would be no misclassifications.

**Comment by egpbos** [comment]
No, currently it just outputs all the (top 5) predictions. This is the output format that was defined in https://github.com/nlesc-sherlock/deeplearning/blob/master/JSON/Example_input_output_Json_specific_model_workflow.md

What should I cutoff? All the tags with a probability below threshold? For the gender case that means you get either one tag (male/female) or zero. In the latter case, what should be done? Leave empty?

**Comment by elboyran** [comment]
I mention in that example the probability threshold!
"The JSON wrapper should look at a part of the JSON at a specific class (string) e.g. {"car","face"}. Also it should consider outputting classification probabilities only above a desired threshold (number), e.g. "0.8". "

You should show only results above the threshold. For this model- 0.6. For other models we have docker images now, we put the value in the issue comment.

**Comment by egpbos** [comment]
Ok, will leave empty then.

Other issue: I didn't copy the classification dicts. Will fix.

**Comment by egpbos** [comment]
Done!
