### ISSUE TITLE
Face detector workflow docker

### ISSUE THREAD

**Issue by cwmeijer** [nlesc-sherlock/deeplearning#87]
A docker image that is based on the general docker. It will accept project specific json as input, adds its results to it and outputs this augmented json file.
- [x] wrapper on github in workflowdocker/<purposename> directory
- [x] on dockerhub (nlescsherlockdl/<purposename>-workflow)

**Comment by elboyran** [comment]
The wrapper is not dumping the json output! :-(

**Comment by egpbos** [comment]
I created two dockers, nlescsherlockdl/face_detector_workflow and nlescsherlockdl/face_detector_workflow_minimal, both are on DockerHub. The minimal version does not include the deeplearning repo, it just copies the necessary files from it, so it's leaner.

To test it, I need input JSON and images. @elboyran could you provide the things you were using on your machine?

**Comment by bpmweel** [comment]
Tested and integrated in workflow.
